import type { Pet } from "@hugg/types";

const daysAgo = (n: number): Date => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
};

export const mockPets: Pet[] = [
  {
    id: "1",
    name: "Bolt",
    species: "DOG",
    breed: "Vira-lata",
    age: 2,
    description: "Cachorro dócil e brincalhão, ótimo com crianças.",
    imageUrls: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
      "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=400",
    ],
    status: "AVAILABLE",
    situation: "SHELTER",
    waitingSince: daysAgo(120),
    createdById: "u1",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: "2",
    name: "Mimi",
    species: "CAT",
    breed: "Siamês",
    age: 1,
    description: "Gatinha curiosa e carinhosa.",
    imageUrls: [
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400",
    ],
    status: "AVAILABLE",
    situation: "FOSTER",
    waitingSince: daysAgo(45),
    createdById: "u1",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: "3",
    name: "Thor",
    species: "DOG",
    breed: "Labrador",
    age: 3,
    description: "Cão grande e tranquilo, gosta de passeios.",
    imageUrls: [
      "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400",
      "https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=400",
      "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=400",
    ],
    status: "AVAILABLE",
    situation: "SHELTER",
    waitingSince: daysAgo(200),
    createdById: "u2",
    createdAt: daysAgo(200),
    updatedAt: daysAgo(0),
  },
  {
    id: "4",
    name: "Nina",
    species: "CAT",
    age: 0,
    description: "Filhote resgatada da rua, muito saudável.",
    imageUrls: [
      "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400",
    ],
    status: "AVAILABLE",
    situation: "ABANDONED",
    waitingSince: daysAgo(10),
    createdById: "u2",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(0),
  },
  {
    id: "5",
    name: "Mel",
    species: "DOG",
    breed: "Poodle",
    age: 5,
    description: "Muito carinhosa, ideal para apartamento.",
    imageUrls: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400",
      "https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?w=400",
    ],
    status: "AVAILABLE",
    situation: "FOSTER",
    waitingSince: daysAgo(60),
    createdById: "u2",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: "6",
    name: "Pipoca",
    species: "RABBIT",
    age: 1,
    description: "Coelho tranquilo, se dá bem com crianças.",
    imageUrls: [
      "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400",
    ],
    status: "AVAILABLE",
    situation: "ABANDONED",
    waitingSince: daysAgo(30),
    createdById: "u1",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: "7",
    name: "Simba",
    species: "CAT",
    breed: "Maine Coon",
    age: 4,
    description: "Gato grande e peludo, muito tranquilo.",
    imageUrls: [
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400",
      "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=400",
    ],
    status: "AVAILABLE",
    situation: "SHELTER",
    waitingSince: daysAgo(90),
    createdById: "u1",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },
  {
    id: "8",
    name: "Rex",
    species: "DOG",
    breed: "Pastor Alemão",
    age: 6,
    description: "Cão treinado, obediente e protetor.",
    imageUrls: [
      "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400",
    ],
    status: "AVAILABLE",
    situation: "SHELTER",
    waitingSince: daysAgo(150),
    createdById: "u2",
    createdAt: daysAgo(150),
    updatedAt: daysAgo(2),
  },
];
