name: Migration for Develop

on:
  push:
    paths:
      - packages/database/prisma/migrations/**
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-migrations:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'develop'
    secrets:
      turso_database_url: ${{ secrets.TURSO_DATABASE_URL_PREVIEW }}
      turso_auth_token: ${{ secrets.TURSO_AUTH_TOKEN_PREVIEW }}
