name: Migration for Production

on:
  push:
    paths:
      - packages/database/prisma/migrations/**
    branches:
      - main
  workflow_dispatch:

jobs:
  run-migrations:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
    secrets:
      turso_database_url: ${{ secrets.TURSO_DATABASE_URL_PRODUCTION }}
      turso_auth_token: ${{ secrets.TURSO_AUTH_TOKEN_PRODUCTION }}
